config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#top'

  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :contacts
  resources :sessions
  resources :users
  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true
    validates :title, length: { maximum: 140 }
    validates :content, presence: true
    validates :content, length: { maximum: 140 }
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :content, presence: true
    validates :content, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum:255 },
              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :login_or_not, only: [:new, :show, :edit, :destroy]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
      @blog.image.retrieve_from_cache! params[:cache][:image]
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    @blog.image.retrieve_from_cache!  params[:cache][:image]

    if @blog.save
      @user = current_user
      CreateMailer.create_mail(@blog).deliver
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    render :new if @blog.invalid?
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  # idをキーとして値を取得するメソッド
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def login_or_not
    if !current_user
      redirect_to new_session_path, notice:"ログインしてください"
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            redirect_to new_contact_path, notice: "お問い合わせを送信しました！"
        else
            render 'new'
        end
    end
    
    private
    def contact_params
        params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_or_not, only: [:update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end

  def update
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
    @user.password = current_user.password_digest
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "アイコンを追加しました！"
    else
      render 'show'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :image_cache)
  end

  def login_or_not
    if !current_user
      redirect_to new_session_path, notice:"ログインしてください"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <div class="blog_title form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class:"form-control" %>
  </div>
  <div class="blog_image">
    <%= form.label :image %>
    <%= image_tag(@blog.image.url) if @blog.image.url %>
    <%= form.file_field :image, id: :blog_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit "送信", class: "btn btn-default" %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="layout">

<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url) %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <div>
    <%= form.submit  "投稿する", class: "btn btn-default" %>
  </div>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
    <%= form.submit "もどる", name: 'back', class: "btn btn-default" %>
<% end %>

</div>

app/views/blogs/edit.html.erb
<div class="layout">

  <h2>ブログを編集する</h2>

  <%= render 'form' %>

</div>

app/views/blogs/index.html.erb
<div class="row layout">
  <h1>ブログ一覧</h1>
  <p><%= notice %></p>
  <% @blogs.each do |blog| %>
    <div class="col-md-6 blog-item">
      <table>
        <tr class="row">
          <th class="col-xs-4">タイトル</th>
          <th class="col-xs-8">内容</th>
        </tr>
        <tr class="row">
          <td class="col-xs-4"><%= blog.title %></td>
          <td class="col-xs-8"><%= blog.content %></td>
        </tr>
      </table>
      <div class="btn-group btn-group-all" role="group" aria-label="...">
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default"><%= link_to '詳細を確認する', blog_path(blog.id) %></button>
        </div>
        <% if logged_in? %>
          <% if current_user.id == blog.user_id %>
            <div class="btn-group" role="group">
              <button type="button" class="btn btn-default"><%= link_to "ブログを編集する", edit_blog_path(blog.id) %></button>
            </div>
            <div class="btn-group" role="group">
              <button type="button" class="btn btn-default"><%= link_to 'ブログを削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></button>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  <% end %>
  <div class="col-sm-12 new-action">
    <p><%= link_to '新しくブログを投稿する', new_blog_path %></p>
    <p><%= link_to 'お問い合わせ', new_contact_path %></p>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="layout">

  <h2>ブログを作成する</h2>

  <%= render 'form' %>

</div>

app/views/blogs/show.html.erb
<div class="layout">

  <h1>ブログ詳細画面</h1>
  <p>タイトル: <%= @blog.title %></p>
  <p>内容: <%= @blog.content %></p>
  <p>Image: <%= image_tag @blog.image %></p>

  <% unless @blog.user == current_user %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id, blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>

  <%= link_to "ブログ一覧画面にもどる", blogs_path %>
</div>

app/views/contacts/new.html.erb
<div class="layout">

<h2>お問い合わせ</h2>
<p><%= notice %></p>

<%= form_with(model: @contact, local: true) do |form| %>

    <% if @contact.errors.any? %>
    <div id="error_explanation">
        <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
        <ul>
            <% @contact.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>

    <div class = "contact_name form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
    </div>
    <div class = "contact_email form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class:"form-control" %>
    </div>
    <div class = "contact_content form-group">
        <%= form.label :content %>
        <%= form.text_field :content, class:"form-control" %>
    </div>
    <%= form.submit "送信", class: 'btn btn btn-default' %>
<% end %>

</div>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>

app/views/users/new.html.erb
<div class="layout">
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
      prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>

<div class="name-form">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="email-form">
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>

<div class="password-form">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div class="password-confirmation-form">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

<div class="user-submit">
  <%= f.submit "Create my account" %>
</div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="layout">
  <h1><%= @user.name %>のページ</h1>
  <%= form_with(model: @user, local: true, url: user_path(@user.id)) do |form| %>
    <div class="user_image">
      <%= form.label :image %>
      <%= image_tag(@user.image.url) if @user.image.url %>
      <%= form.file_field :image, id: :user_image %>
      <%= form.hidden_field :image_cache %>
    </div>
    <%= form.submit "登録", class: "btn btn-default" %>
  <% end %>
<!-- <p><%= image_tag @user.image %></p> -->
<p>メールアドレス:
  <%= @user.email %></p>
<p>＜お気に入りBlog＞</p>
<% @favorite_blogs.each do |blog| %>
  <p>タイトル:
    <%= blog.title %>
    内容:
    <%= blog.content %>
    <button type="button" class="btn btn-default"><%= link_to '詳細を確認する', blog_path(blog.id) %></button>
  </p>
<% end %>
</div>