config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#top'

  resources :blogs do
    collection do
      post :confirm
    end
  end

  resources :contacts
  resources :sessions
  resources :users
  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true
    validates :title, length: { maximum: 140 }
    validates :content, presence: true
    validates :content, length: { maximum: 140 }
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :content, presence: true
    validates :content, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum:255 },
              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  mount_uploader :image, ImageUploader
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :login_or_not, only: [:new, :show, :edit, :destroy]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
      @blog.image.retrieve_from_cache! params[:cache][:image]
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    @blog.image.retrieve_from_cache!  params[:cache][:image]

    if @blog.save
      @user = current_user
      CreateMailer.create_mail(@blog).deliver
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #現在ログインしているuserのidをblogのuser_idカラムに挿入する。
    render :new if @blog.invalid?
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  # idをキーとして値を取得するメソッド
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def login_or_not
    if !current_user
      redirect_to new_session_path, notice:"ログインしてください"
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            redirect_to new_contact_path, notice: "お問い合わせを送信しました！"
        else
            render 'new'
        end
    end
    
    private
    def contact_params
        params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_or_not, only: [:update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
  end

  def update
    @user = User.find(params[:id])
    @favorite_blogs = @user.favorite_blogs
    @user.password = current_user.password_digest
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "アイコンを追加しました！"
    else
      render 'show'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :image_cache)
  end

  def login_or_not
    if !current_user
      redirect_to new_session_path, notice:"ログインしてください"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">Blog</a>
          </div>
            <ul class="nav navbar-nav header-menu">
              <li>
                <%= link_to "TOP", "/" %>
              </li>
              <li>
                <%= link_to "ブログ一覧", blogs_path %>
              </li>
              <li>
                <%= link_to "新規投稿", new_blog_path %>
              </li>
              <li>
                <%= link_to "お問合せ", new_contact_path %>
              </li>
            </ul>
            <% if logged_in? %>
              <ul class="nav navbar-nav login-status">
                <li>
                  <%= link_to "Profile", user_path(current_user.id) %>
                </li>
                <li>
                  <%= link_to "Logout", session_path(current_user.id), method: :delete %>
                </li>
              </ul>
              <% else %>
                <ul class="nav navbar-nav login-status">
                  <li>
                    <%= link_to "Sign up", new_user_path %>
                  </li>
                  <li>
                    <%= link_to "Login", new_session_path %>
                  </li>
                <% end %>
              </ul>
        </nav>

        <!-- <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %> -->

        <%= yield %>

        <footer class="navbar navbar-inverse">
          <p class="footer_inner">Dive into Code test application</p>
        </footer>
      </div>
    </body>
  </html>

app/views/pages/top.html.erb
<div class="top-image">
  <img src="blog.top.jpg">
  <div class="top-message">
    <h1>Blog</h1>
    <p>~Start your New Life from here~</p>
  </div>
</div>

<div class="top-explanation">
  <h2>About Blog</h2>
  <p>
    Blogは日々の出来事や思ったことを投稿できるサービスです。<br>
    Blogを利用する事であたなの生活に彩りが加わり、新しい生活が始まる事でしょう。
  </p>
  <p>
    ヘッダーはスマホサイズになった時にハンバーガーメニューになる仕様です。<br>
    ブログ一覧画面では、PCサイズ以上では２列表示になるようなレスポンシブデザインです。
  </p>
</div>